/**
 * ImageClassification
 * service for image classification
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ImageClassification) {
      root.ImageClassification = {};
    }
    root.ImageClassification.OutputParameters = factory(root.ImageClassification.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The OutputParameters model module.
   * @module model/OutputParameters
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>OutputParameters</code>.
   * @alias module:model/OutputParameters
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>OutputParameters</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OutputParameters} obj Optional instance to populate.
   * @return {module:model/OutputParameters} The populated <code>OutputParameters</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('answer')) {
        obj['answer'] = ApiClient.convertToType(data['answer'], Object);
      }
    }
    return obj;
  }

  /**
   * vector
   * @member {Object} answer
   */
  exports.prototype['answer'] = undefined;



  return exports;
}));


