/*
 * DeployRClient
 * Integration technology for deploying R and Python analytics inside web, desktop, mobile, and dashboard applications as well as backend systems. Turn your R or Python scripts into analytics web services, so code can be easily executed by applications running on a secure server.  The core APIs can be grouped into several categories, including: [Authentication](#authentication-apis), [Web Services](#services-management-apis), [Sessions](#session-apis), [Snapshots](#snapshot-apis), [Status](#status-apis), and [Centralized Configuration](#centralized-configuration-apis). 
 *
 * OpenAPI spec version: 9.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.WorkspaceObject;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ExecuteRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-28T05:42:17.706Z")
public class ExecuteRequest {
  @SerializedName("code")
  private String code = null;

  @SerializedName("inputParameters")
  private List<WorkspaceObject> inputParameters = null;

  @SerializedName("outputParameters")
  private List<String> outputParameters = null;

  public ExecuteRequest code(String code) {
    this.code = code;
    return this;
  }

   /**
   * code to execute. **&lt;font color &#x3D; &#39;red&#39;&gt;Required&lt;/font&gt;**
   * @return code
  **/
  @ApiModelProperty(value = "code to execute. **<font color = 'red'>Required</font>**")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public ExecuteRequest inputParameters(List<WorkspaceObject> inputParameters) {
    this.inputParameters = inputParameters;
    return this;
  }

  public ExecuteRequest addInputParametersItem(WorkspaceObject inputParametersItem) {
    if (this.inputParameters == null) {
      this.inputParameters = new ArrayList<WorkspaceObject>();
    }
    this.inputParameters.add(inputParametersItem);
    return this;
  }

   /**
   * Input parameters for the execution. **Optional**
   * @return inputParameters
  **/
  @ApiModelProperty(value = "Input parameters for the execution. **Optional**")
  public List<WorkspaceObject> getInputParameters() {
    return inputParameters;
  }

  public void setInputParameters(List<WorkspaceObject> inputParameters) {
    this.inputParameters = inputParameters;
  }

  public ExecuteRequest outputParameters(List<String> outputParameters) {
    this.outputParameters = outputParameters;
    return this;
  }

  public ExecuteRequest addOutputParametersItem(String outputParametersItem) {
    if (this.outputParameters == null) {
      this.outputParameters = new ArrayList<String>();
    }
    this.outputParameters.add(outputParametersItem);
    return this;
  }

   /**
   * Output parameters for the execution. **Optional**
   * @return outputParameters
  **/
  @ApiModelProperty(value = "Output parameters for the execution. **Optional**")
  public List<String> getOutputParameters() {
    return outputParameters;
  }

  public void setOutputParameters(List<String> outputParameters) {
    this.outputParameters = outputParameters;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExecuteRequest executeRequest = (ExecuteRequest) o;
    return Objects.equals(this.code, executeRequest.code) &&
        Objects.equals(this.inputParameters, executeRequest.inputParameters) &&
        Objects.equals(this.outputParameters, executeRequest.outputParameters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, inputParameters, outputParameters);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExecuteRequest {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    inputParameters: ").append(toIndentedString(inputParameters)).append("\n");
    sb.append("    outputParameters: ").append(toIndentedString(outputParameters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

