/* 
 * ManualTransmissionService
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using ManualTransmissionClient.Client;
using ManualTransmissionClient.Api;
using ManualTransmissionClient.Model;

namespace ManualTransmissionClient.Test
{
    /// <summary>
    ///  Class for testing UserApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class UserApiTests
    {
        private UserApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new UserApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' UserApi
            //Assert.IsInstanceOfType(typeof(UserApi), instance, "instance is a UserApi");
        }

        
        /// <summary>
        /// Test Login
        /// </summary>
        [Test]
        public void LoginTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //LoginRequest loginRequest = null;
            //var response = instance.Login(loginRequest);
            //Assert.IsInstanceOf<AccessTokenResponse> (response, "response is AccessTokenResponse");
        }
        
        /// <summary>
        /// Test RenewToken
        /// </summary>
        [Test]
        public void RenewTokenTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RenewTokenRequest renewTokenRequest = null;
            //var response = instance.RenewToken(renewTokenRequest);
            //Assert.IsInstanceOf<AccessTokenResponse> (response, "response is AccessTokenResponse");
        }
        
        /// <summary>
        /// Test RevokeRefreshToken
        /// </summary>
        [Test]
        public void RevokeRefreshTokenTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string refreshToken = null;
            //var response = instance.RevokeRefreshToken(refreshToken);
            //Assert.IsInstanceOf<AccessTokenResponse> (response, "response is AccessTokenResponse");
        }
        
    }

}
