/*
 * rainService
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * OutputParameters
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-07T04:54:43.579Z")
public class OutputParameters {
  @SerializedName("pred")
  private BigDecimal pred = null;

  public OutputParameters pred(BigDecimal pred) {
    this.pred = pred;
    return this;
  }

   /**
   * numeric
   * @return pred
  **/
  @ApiModelProperty(value = "numeric")
  public BigDecimal getPred() {
    return pred;
  }

  public void setPred(BigDecimal pred) {
    this.pred = pred;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OutputParameters outputParameters = (OutputParameters) o;
    return Objects.equals(this.pred, outputParameters.pred);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pred);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OutputParameters {\n");
    
    sb.append("    pred: ").append(toIndentedString(pred)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

