/*
 * DeployRClient
 * Integration technology for deploying R and Python analytics inside web, desktop, mobile, and dashboard applications as well as backend systems. Turn your R or Python scripts into analytics web services, so code can be easily executed by applications running on a secure server.  The core APIs can be grouped into several categories, including: [Authentication](#authentication-apis), [Web Services](#services-management-apis), [Sessions](#session-apis), [Snapshots](#snapshot-apis), [Status](#status-apis), and [Centralized Configuration](#centralized-configuration-apis). 
 *
 * OpenAPI spec version: 9.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Error;
import io.swagger.client.model.GetComputeNodesResponse;
import io.swagger.client.model.UpdateComputeNodesRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CentralizedConfigurationAPIsApi
 */
@Ignore
public class CentralizedConfigurationAPIsApiTest {

    private final CentralizedConfigurationAPIsApi api = new CentralizedConfigurationAPIsApi();

    
    /**
     * Add Compute Node
     *
     * Add Compute Node URIs or Ranges to list.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addComputeNodeTest() throws ApiException {
        UpdateComputeNodesRequest entries = null;
        api.addComputeNode(entries);

        // TODO: test validations
    }
    
    /**
     * Get Compute Nodes
     *
     * Lists all existing compute node uris.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getComputeNodesTest() throws ApiException {
        GetComputeNodesResponse response = api.getComputeNodes();

        // TODO: test validations
    }
    
    /**
     * Remove Compute Node
     *
     * Remove Compute Node URIs or Ranges from list.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removeComputeNodeTest() throws ApiException {
        UpdateComputeNodesRequest entries = null;
        api.removeComputeNode(entries);

        // TODO: test validations
    }
    
    /**
     * Set Compute Nodes
     *
     * Sets entire list of compute node uris, overriding previous entries.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void setComputeNodesTest() throws ApiException {
        UpdateComputeNodesRequest entries = null;
        api.setComputeNodes(entries);

        // TODO: test validations
    }
    
}
