// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace FlightService.Models
{
    using System.Linq;

    public partial class OutputParameters
    {
        /// <summary>
        /// Initializes a new instance of the OutputParameters class.
        /// </summary>
        public OutputParameters() { }

        /// <summary>
        /// Initializes a new instance of the OutputParameters class.
        /// </summary>
        /// <param name="answer">data.frame</param>
        public OutputParameters(object answer = default(object))
        {
            Answer = answer;
        }

        /// <summary>
        /// Gets or sets data.frame
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "answer")]
        public object Answer { get; set; }

    }
}
