// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ValidateSetup.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class InputParameters
    {
        /// <summary>
        /// Initializes a new instance of the InputParameters class.
        /// </summary>
        public InputParameters()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the InputParameters class.
        /// </summary>
        /// <param name="hp">numeric</param>
        /// <param name="wt">numeric</param>
        public InputParameters(double? hp = default(double?), double? wt = default(double?))
        {
            Hp = hp;
            Wt = wt;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets numeric
        /// </summary>
        [JsonProperty(PropertyName = "hp")]
        public double? Hp { get; set; }

        /// <summary>
        /// Gets or sets numeric
        /// </summary>
        [JsonProperty(PropertyName = "wt")]
        public double? Wt { get; set; }

    }
}
