// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ValidateSetup.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for RuntimeType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum RuntimeType
    {
        [EnumMember(Value = "R")]
        R,
        [EnumMember(Value = "Python")]
        Python
    }
}
