/* 
 * ManualTransmissionService
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ManualTransmissionClient.Api;
using ManualTransmissionClient.Model;
using ManualTransmissionClient.Client;
using System.Reflection;

namespace ManualTransmissionClient.Test
{
    /// <summary>
    ///  Class for testing AccessTokenResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AccessTokenResponseTests
    {
        // TODO uncomment below to declare an instance variable for AccessTokenResponse
        //private AccessTokenResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AccessTokenResponse
            //instance = new AccessTokenResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccessTokenResponse
        /// </summary>
        [Test]
        public void AccessTokenResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AccessTokenResponse
            //Assert.IsInstanceOfType<AccessTokenResponse> (instance, "variable 'instance' is a AccessTokenResponse");
        }

        /// <summary>
        /// Test the property 'TokenType'
        /// </summary>
        [Test]
        public void TokenTypeTest()
        {
            // TODO unit test for the property 'TokenType'
        }
        /// <summary>
        /// Test the property 'AccessToken'
        /// </summary>
        [Test]
        public void AccessTokenTest()
        {
            // TODO unit test for the property 'AccessToken'
        }
        /// <summary>
        /// Test the property 'ExpiresOn'
        /// </summary>
        [Test]
        public void ExpiresOnTest()
        {
            // TODO unit test for the property 'ExpiresOn'
        }
        /// <summary>
        /// Test the property 'RefreshToken'
        /// </summary>
        [Test]
        public void RefreshTokenTest()
        {
            // TODO unit test for the property 'RefreshToken'
        }

    }

}
