/* 
 * ManualTransmissionService
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ManualTransmissionClient.Api;
using ManualTransmissionClient.Model;
using ManualTransmissionClient.Client;
using System.Reflection;

namespace ManualTransmissionClient.Test
{
    /// <summary>
    ///  Class for testing BatchWebServiceResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BatchWebServiceResultTests
    {
        // TODO uncomment below to declare an instance variable for BatchWebServiceResult
        //private BatchWebServiceResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BatchWebServiceResult
            //instance = new BatchWebServiceResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BatchWebServiceResult
        /// </summary>
        [Test]
        public void BatchWebServiceResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BatchWebServiceResult
            //Assert.IsInstanceOfType<BatchWebServiceResult> (instance, "variable 'instance' is a BatchWebServiceResult");
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'CompletedItemCount'
        /// </summary>
        [Test]
        public void CompletedItemCountTest()
        {
            // TODO unit test for the property 'CompletedItemCount'
        }
        /// <summary>
        /// Test the property 'TotalItemCount'
        /// </summary>
        [Test]
        public void TotalItemCountTest()
        {
            // TODO unit test for the property 'TotalItemCount'
        }
        /// <summary>
        /// Test the property 'BatchExecutionResults'
        /// </summary>
        [Test]
        public void BatchExecutionResultsTest()
        {
            // TODO unit test for the property 'BatchExecutionResults'
        }

    }

}
