/* 
 * ManualTransmissionService
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ManualTransmissionClient.Api;
using ManualTransmissionClient.Model;
using ManualTransmissionClient.Client;
using System.Reflection;

namespace ManualTransmissionClient.Test
{
    /// <summary>
    ///  Class for testing InputParameters
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InputParametersTests
    {
        // TODO uncomment below to declare an instance variable for InputParameters
        //private InputParameters instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InputParameters
            //instance = new InputParameters();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InputParameters
        /// </summary>
        [Test]
        public void InputParametersInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InputParameters
            //Assert.IsInstanceOfType<InputParameters> (instance, "variable 'instance' is a InputParameters");
        }

        /// <summary>
        /// Test the property 'Hp'
        /// </summary>
        [Test]
        public void HpTest()
        {
            // TODO unit test for the property 'Hp'
        }
        /// <summary>
        /// Test the property 'Wt'
        /// </summary>
        [Test]
        public void WtTest()
        {
            // TODO unit test for the property 'Wt'
        }

    }

}
