/* 
 * ManualTransmissionService
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ManualTransmissionClient.Api;
using ManualTransmissionClient.Model;
using ManualTransmissionClient.Client;
using System.Reflection;

namespace ManualTransmissionClient.Test
{
    /// <summary>
    ///  Class for testing LoginRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LoginRequestTests
    {
        // TODO uncomment below to declare an instance variable for LoginRequest
        //private LoginRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LoginRequest
            //instance = new LoginRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LoginRequest
        /// </summary>
        [Test]
        public void LoginRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoginRequest
            //Assert.IsInstanceOfType<LoginRequest> (instance, "variable 'instance' is a LoginRequest");
        }

        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Test]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Test]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

    }

}
