/* 
 * ManualTransmissionService
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ManualTransmissionClient.Api;
using ManualTransmissionClient.Model;
using ManualTransmissionClient.Client;
using System.Reflection;

namespace ManualTransmissionClient.Test
{
    /// <summary>
    ///  Class for testing RenewTokenRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RenewTokenRequestTests
    {
        // TODO uncomment below to declare an instance variable for RenewTokenRequest
        //private RenewTokenRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RenewTokenRequest
            //instance = new RenewTokenRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RenewTokenRequest
        /// </summary>
        [Test]
        public void RenewTokenRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RenewTokenRequest
            //Assert.IsInstanceOfType<RenewTokenRequest> (instance, "variable 'instance' is a RenewTokenRequest");
        }

        /// <summary>
        /// Test the property 'RefreshToken'
        /// </summary>
        [Test]
        public void RefreshTokenTest()
        {
            // TODO unit test for the property 'RefreshToken'
        }

    }

}
