/**
 * ImageClassification
 * service for image classification
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ImageClassification);
  }
}(this, function(expect, ImageClassification) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ImageClassification.WebServiceResult();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('WebServiceResult', function() {
    it('should create an instance of WebServiceResult', function() {
      // uncomment below and update the code to test WebServiceResult
      //var instane = new ImageClassification.WebServiceResult();
      //expect(instance).to.be.a(ImageClassification.WebServiceResult);
    });

    it('should have the property success (base name: "success")', function() {
      // uncomment below and update the code to test the property success
      //var instane = new ImageClassification.WebServiceResult();
      //expect(instance).to.be();
    });

    it('should have the property errorMessage (base name: "errorMessage")', function() {
      // uncomment below and update the code to test the property errorMessage
      //var instane = new ImageClassification.WebServiceResult();
      //expect(instance).to.be();
    });

    it('should have the property consoleOutput (base name: "consoleOutput")', function() {
      // uncomment below and update the code to test the property consoleOutput
      //var instane = new ImageClassification.WebServiceResult();
      //expect(instance).to.be();
    });

    it('should have the property changedFiles (base name: "changedFiles")', function() {
      // uncomment below and update the code to test the property changedFiles
      //var instane = new ImageClassification.WebServiceResult();
      //expect(instance).to.be();
    });

    it('should have the property outputParameters (base name: "outputParameters")', function() {
      // uncomment below and update the code to test the property outputParameters
      //var instane = new ImageClassification.WebServiceResult();
      //expect(instance).to.be();
    });

  });

}));
