/* 
 * ManualTransmissionService
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ManualTransmissionClient.Client.SwaggerDateConverter;

namespace ManualTransmissionClient.Model
{
    /// <summary>
    /// InputParameters
    /// </summary>
    [DataContract]
    public partial class InputParameters :  IEquatable<InputParameters>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InputParameters" /> class.
        /// </summary>
        /// <param name="Hp">numeric.</param>
        /// <param name="Wt">numeric.</param>
        public InputParameters(decimal? Hp = default(decimal?), decimal? Wt = default(decimal?))
        {
            this.Hp = Hp;
            this.Wt = Wt;
        }
        
        /// <summary>
        /// numeric
        /// </summary>
        /// <value>numeric</value>
        [DataMember(Name="hp", EmitDefaultValue=false)]
        public decimal? Hp { get; set; }

        /// <summary>
        /// numeric
        /// </summary>
        /// <value>numeric</value>
        [DataMember(Name="wt", EmitDefaultValue=false)]
        public decimal? Wt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InputParameters {\n");
            sb.Append("  Hp: ").Append(Hp).Append("\n");
            sb.Append("  Wt: ").Append(Wt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as InputParameters);
        }

        /// <summary>
        /// Returns true if InputParameters instances are equal
        /// </summary>
        /// <param name="other">Instance of InputParameters to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InputParameters other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Hp == other.Hp ||
                    this.Hp != null &&
                    this.Hp.Equals(other.Hp)
                ) && 
                (
                    this.Wt == other.Wt ||
                    this.Wt != null &&
                    this.Wt.Equals(other.Wt)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Hp != null)
                    hash = hash * 59 + this.Hp.GetHashCode();
                if (this.Wt != null)
                    hash = hash * 59 + this.Wt.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
