// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace HotelOperatingMargin.Models
{
    using System.Linq;

    public partial class InputParameters
    {
        /// <summary>
        /// Initializes a new instance of the InputParameters class.
        /// </summary>
        public InputParameters() { }

        /// <summary>
        /// Initializes a new instance of the InputParameters class.
        /// </summary>
        /// <param name="totalRooms">numeric</param>
        /// <param name="nearestCompetition">numeric</param>
        /// <param name="annualVisitors">numeric</param>
        /// <param name="medianIncome">numeric</param>
        public InputParameters(double? totalRooms = default(double?), double? nearestCompetition = default(double?), double? annualVisitors = default(double?), double? medianIncome = default(double?))
        {
            TotalRooms = totalRooms;
            NearestCompetition = nearestCompetition;
            AnnualVisitors = annualVisitors;
            MedianIncome = medianIncome;
        }

        /// <summary>
        /// Gets or sets numeric
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "TotalRooms")]
        public double? TotalRooms { get; set; }

        /// <summary>
        /// Gets or sets numeric
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "NearestCompetition")]
        public double? NearestCompetition { get; set; }

        /// <summary>
        /// Gets or sets numeric
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "AnnualVisitors")]
        public double? AnnualVisitors { get; set; }

        /// <summary>
        /// Gets or sets numeric
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "MedianIncome")]
        public double? MedianIncome { get; set; }

    }
}
